name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./MiddleWare
    - name: Build
      run: dotnet build --no-restore --configuration Release
      working-directory: ./MiddleWare
    - name: Pack      
      run: dotnet pack --configuration Release --no-build --output ./nupkgs
      working-directory: ./MiddleWare
      
    - uses: actions/upload-artifact@v4
      with:
        name: Autorizacion.Middleware
        if-no-files-found: error
        retention-days: 7
        path: /home/runner/work/Middleware/Middleware/MiddleWare/*/*/*/*.nupkg

  release:
    runs-on: ubuntu-latest    
    needs: build
    steps:  
    - name: Checkout 
      uses: actions/checkout@v4
    
    - name: Downlod Artifacts 
      uses: actions/download-artifact@v4
    
    - name: List Files
      run: ls -R
      
    - name: Prep packages
      run: dotnet nuget add source --username Isma-L154 --password ${{ secrets.NUGET_TOKEN }} --store-password-in-clear-text --name Package "https://nuget.pkg.github.com/Isma-L154/index.json"
    - name: Push package to GitHub packages 
      run: dotnet nuget push Autorizacion.Middleware/*/*/*/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }}  --source "Package" --skip-duplicate
